### ISSUE TITLE
Confusing error when browser is missing

### ISSUE THREAD

**Issue by kumavis** [hughsk/smokestack#60]
```
➜ browserify index.js | smokestack
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at launchChrome (/home/xyz/.nvm/versions/node/v10.16.0/lib/node_modules/smokestack/node_modules/chrome-launch/index.js:27:12)
    at launchBrowser (/home/xyz/.nvm/versions/node/v10.16.0/lib/node_modules/smokestack/index.js:196:20)
    at open (/home/xyz/.nvm/versions/node/v10.16.0/lib/node_modules/smokestack/index.js:139:9)
    at DestroyableTransform.flush [as _flush] (/home/xyz/.nvm/versions/node/v10.16.0/lib/node_modules/smokestack/index.js:133:24)
    at DestroyableTransform.<anonymous> (/home/xyz/.nvm/versions/node/v10.16.0/lib/node_modules/smokestack/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)

```

**Comment by kumavis** [comment]
I guess I was missing `google-chrome`
